### ISSUE TITLE
THEY DID IT AGAIN

### ISSUE THREAD

**Issue by ghost** [DeltaNeverUsed/reddit-place-script-2022#10]
canvas was doubled again, this time down.

**Comment by DeltaNeverUsed** [comment]
i know, i've already updated it

**Comment by ghost** [comment]
lightning fast developer is at it

**Comment by ghost** [comment]
oh shit did u do colors too?

**Comment by DeltaNeverUsed** [comment]
yup

**Comment by DeltaNeverUsed** [comment]
i'll close this issue now, feel free to create a new one if issues occur
