### ISSUE TITLE
Bots constantly replace top left pixel when there's nothing else to do

### ISSUE THREAD

**Issue by qixils** [DeltaNeverUsed/reddit-place-script-2022#14]
It's not a huge deal considering how the bots cycle, though it does seem like a good way to get the ire of reddit (i.e. make them suspicious of your account(s))

![image](https://user-images.githubusercontent.com/13265322/161446372-3f066b2c-e1bd-4a37-8214-83c57a3809c3.png)

And yes, I was watching the canvas and can confirm that the image was 100% matched and that the bots were just replacing the same pixel repeatedly

**Comment by DeltaNeverUsed** [comment]
When it's complete it should now just sleep for 2 minutes before checking the board again, as well as not placing a pixel

**Comment by thecosmicskye** [comment]
@DeltaNeverUsed It's now placing the top left corner no matter what. Every account is filling it in no matter what. It won't move onto the next pixel on a new canvas.

**Comment by qixils** [comment]
are you on the latest commit? seems fine for me (at least in canvas 1)

**Comment by thecosmicskye** [comment]
@qixils Yeah, I think the latest latest one just fixed it.

**Comment by thecosmicskye** [comment]
@qixils ah, my bad, still same issue.
