### ISSUE TITLE
Still filling same pixel over and over in latest commit

### ISSUE THREAD

**Issue by thecosmicskye** [DeltaNeverUsed/reddit-place-script-2022#16]
![image](https://user-images.githubusercontent.com/7584038/161447446-c54b626c-7dca-4506-8bae-a2c581ebef68.png)
![image](https://user-images.githubusercontent.com/7584038/161447434-9bbc2ad5-08bb-4b6a-92b8-db2a57f7f4f3.png)

I know that's not right because this is in the new canvas, and I'm watching it and it is already filled with the color I want.

**Comment by DeltaNeverUsed** [comment]
i found the issue, give me a few minutes

**Comment by DeltaNeverUsed** [comment]
try again now

**Comment by thecosmicskye** [comment]
@DeltaNeverUsed confirmed fixed :)

**Comment by thecosmicskye** [comment]
Wow speedy quick. 10/10 stars
