### ISSUE TITLE
Bad .env with multiple accounts

### ISSUE THREAD

**Issue by colingoodman** [DeltaNeverUsed/reddit-place-script-2022#2]
Script takes the `.env` with multiple accounts, but doesn't seem to recognize any after the first. My `.env` file looks roughly like the following, with params redacted for privacy:

```ENV_PLACE_USERNAME=["...","...","..."]
ENV_PLACE_PASSWORD=["...","...","..."]
ENV_PLACE_APP_CLIENT_ID=["...","...","..."]
ENV_PLACE_SECRET_KEY=["...","...","..."]
ENV_DRAW_X_START="x"
ENV_DRAW_Y_START="y"
```

This is adapted from the `.env` used by the original repo this was forked from; it takes fine there.

Edit: Verified issue with bad .env, but script still ignores multiple accounts.

**Comment by colingoodman** [comment]
Resolved original issue (lists were different lengths) and found that the script does utilize all accounts properly, just moves slowly.

**Comment by DeltaNeverUsed** [comment]
> found that the script does utilize all accounts properly

sorry to open a closed issue again, but what do you mean by this?
