### ISSUE TITLE
list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by agent-guardian** [DeltaNeverUsed/reddit-place-script-2022#3]
a few of my accounts are getting this error and aren't drawing a pixel. Not all of my accounts have this problem though.
```list indices must be integers or slices, not str```

**Comment by agent-guardian** [comment]
actually this error is occurring after the pixel is placed, when a error json string is returned by the server.

**Comment by DeltaNeverUsed** [comment]
Download the new version, this has been fixed
