### ISSUE TITLE
Pixels placing slow with multiple accounts

### ISSUE THREAD

**Issue by tylerval18** [DeltaNeverUsed/reddit-place-script-2022#6]
I set the delay to 0 and it still takes over 20+ seconds to place a pixel, I would want this to be faster as I have over 30 accounts. Is there anyway to place the pixels faster?

**Comment by DeltaNeverUsed** [comment]
It's probably limited by the set pixel post request
since it's not multithreaded, it waits for the last one to be finished before continuing

**Comment by Kasax007** [comment]
In previous versions it was much much faster. So I really want this fixed since it limits me to the old canvas.

**Comment by DeltaNeverUsed** [comment]
i could fix it, give me a minute

**Comment by DeltaNeverUsed** [comment]
should be fine now

**Comment by DeltaNeverUsed** [comment]
i'm going to close this issue now
