### ISSUE TITLE
Proxy support?

### ISSUE THREAD

**Issue by ghost** [DeltaNeverUsed/reddit-place-script-2022#7]
The main script supports proxies to bypass ratelimiting since more than 2 accounts is nearly guaranteed to make you get ratelimited. Does this script also support proxies?

**Comment by ghost** [comment]
NVM your script uses tor already, didn't notice :p

**Comment by DeltaNeverUsed** [comment]
Only for the actual set pixel post request, so it's not fully supported

**Comment by ghost** [comment]
Should i put all accounts in just one instance or should i make more instances?
Or to be more specific does it update the circuit every time it tries to place?

**Comment by DeltaNeverUsed** [comment]
it's a new circuit every time
