### ISSUE TITLE
Error : sleep length must be non-negative

### ISSUE THREAD

**Issue by botcoder-sys** [DeltaNeverUsed/reddit-place-script-2022#9]
Hello, I am getting this error. I am using the recent main.py file with multiple accounts. 
 main.py", line 469, in <module>
    time.sleep((pixel_place_frequency/len(accounts))+1-time_taken)
ValueError: sleep length must be non-negative

**Comment by DeltaNeverUsed** [comment]
it's now fixed

**Comment by botcoder-sys** [comment]
@DeltaNeverUsed Traceback (most recent call last):
  File "E:\reddit-place-script-2022-main\main.py", line 502, in <module>
    time.sleep(clamp(pixel_place_frequency/len(accounts))+1-time_taken, 1, 99999999)
NameError: name 'clamp' is not defined 
I am getting this error now

**Comment by DeltaNeverUsed** [comment]
i'm stupid, try now

**Comment by botcoder-sys** [comment]
@DeltaNeverUsed Traceback (most recent call last):
  File "E:\reddit-place-script-2022-main\main.py", line 505, in <module>
    time.sleep(clamp(pixel_place_frequency/len(accounts))+1-time_taken, 1, 99999999)
TypeError: clamp() missing 2 required positional arguments: 'a' and 'b'

**Comment by DeltaNeverUsed** [comment]
just fixed that
